### ISSUE TITLE
Ran into error when compiling the doc

### ISSUE THREAD

**Issue by ziqingluo** [Frama-C/Qed#2]
I got the following error when I try to "make doc":
`Generating 'Qed' documentation
+ ocamlfind ocamldoc -dump src/logic.odoc -t 'Qed Library' -short-functors -I src src/logic.mli
File "/Users/ziqing/Documents/repos/Qed/_build/src/logic.mli", line 524:
[Not_found] is not a valid exception constructor in "@raise [Not_found] if no type is found."
1 error(s) encountered
Command exited with code 1.
Compilation unsuccessful after building 52 targets (0 cached) in 00:00:01.
make: *** [doc] Error 10`

I'm using a Mac.

**Comment by ziqingluo** [comment]
I updated the repo and the doc can be generated successfully now after I installed Jbuilder.

**Comment by correnson** [comment]
Thanks for the report. Actually we have a branch using jbuilder too in preparation.
